### ISSUE TITLE
Naming Changes

### ISSUE THREAD

**Issue by Raistlfiren** [caxiam/sqlalchemy-jsonapi-collections#7]
Your classes are named differently based upon the parameter type  - https://github.com/caxiam/sqlalchemy-jsonapi-collections/blob/master/flask_sqlalchemy_jsonapi/__init__.py#L7

Would it be better to name them similarly? For example, IncludeValue to IncludeParameter and SortValue to SortParameter. Just a thought.

Thanks!

**Comment by cmanallen** [comment]
@Raistlfiren The classes are named after what they represent.  Consider the following URL.

```
...com/endpoint?filter[field_1]=wow,test&filter[field_2]=test&sort=-field_1,field_2&include=field_2
```

This URL would be represented as two `FilterParameter` instances (even though three filter values were provided), two `SortValue` instances (even though only one sort parameter exists), and one `IncludeValue` instance.

The `FilterParameter` class represents the entirety of the key, value pair.  The `SortValue` class represents a single value of the `sort` parameter.  That's the reason for the naming discrepancy.  They simply represent different things.

Hope this helps.

**Comment by Raistlfiren** [comment]
Oh cool, thanks for the clarification.
